name = "HorseySet"
uuid = "65504333-5517-4a9d-bc3a-2d3cb10b58b6"
authors = ["Andrew Dolgert <github@dolgert.com>"]
version = "1.0.0-DEV"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
BenchmarkTools = "1.6.0"
DataStructures = "0.18.22"
OrderedCollections = "1.8.1"
julia = "1.11.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
